version: "3.4"

# x-defaults:
#   &working_dir: /go/src/github.com/boomfunc/base
#   &logging
#     options:
#       max-size: "1m"

services:

    geo:
      image: boomfunc/geo
      environment:
        - BMP_DEBUG_MODE=true
      ports:
          - "8080:8080"

    build:
        image: golang
        volumes:
            - src-vol:/go/src/github.com/boomfunc/base
            - src-vol:/go/bin
        working_dir: /go/src/github.com/boomfunc/base
        environment:
            # - GOBIN=/go/src/bin/app
            - GOOS=darwin
            - GOARCH=amd64
        command: sh -c "go get -v -d ./...; go install -v ./..."

    test:
        image: golang
        volumes:
            - src-vol:/go/src/github.com/boomfunc/base
        working_dir: /go/src/github.com/boomfunc/base
        command: sh -c "go get -v -d -t ./...; go test ./... -v -race -cover"

    bench:
        image: golang
        volumes:
            - src-vol:/go/src/github.com/boomfunc/base
        working_dir: /go/src/github.com/boomfunc/base
        command: sh -c "go get -v -d -t ./...; go test ./... -v -run=^$$ -bench=. -benchmem"

    fmt:
        image: golang
        volumes:
            - src-vol:/go/src/github.com/boomfunc/base
        working_dir: /go/src/github.com/boomfunc/base
        command: sh -c "go fix ./...; go vet ./...; go fmt ./..."

volumes:
    src-vol:
        driver_opts:
            type: none
            device: ${PWD}
            o: bind
