version: "3.4"

x-defaults:

  volumes: &volumes
    - src-vol:/go/src/github.com/boomfunc/base
    - bin-vol:/go/bin

  logging: &logging
    options:
      max-size: 200k

  working_dir: &working_dir
    /go/src/github.com/boomfunc/base

services:

  geo:
    image: golang:alpine
    environment:
      - BMP_DEBUG_MODE=true
      - BMP_CONFIG=./geo/conf.yml
    ports:
        - "8080:8080"
    volumes: *volumes
    working_dir: *working_dir
    logging: *logging
    command: .circleci/scripts/run.sh

  # geo:
  #   build:
  #     context: ./geo
  #   environment:
  #     - BMP_DEBUG_MODE=true
  #     # - BMP_CONFIG=./conf/example.yml
  #   ports:
  #       - "8080:8080"
  #   logging: *logging

  build:
    image: golang
    volumes: *volumes
    working_dir: *working_dir
    logging: *logging
    command: .circleci/scripts/build.sh

  test:
    image: golang
    volumes: *volumes
    working_dir: *working_dir
    logging: *logging
    command: .circleci/scripts/test.sh

  bench:
    image: golang
    volumes: *volumes
    working_dir: *working_dir
    logging: *logging
    command: .circleci/scripts/bench.sh

  fmt:
    image: golang
    volumes: *volumes
    working_dir: *working_dir
    logging: *logging
    command: .circleci/scripts/fmt.sh

  # *:
  #   image: golang
  #   volumes: *volumes
  #   working_dir: *working_dir
  #   logging: *logging
  #   command: .circleci/scripts/docker-entrypoint.sh

volumes:
  src-vol:
    driver_opts:
      type: none
      device: ${PWD}
      o: bind

  bin-vol:
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
