version: 2
jobs:

  test:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/boomfunc/base

    steps:
      - checkout
      - run: go get -v -d -t ./...
      - run: go test -v -race -cover ./...


  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/boomfunc/base

    steps:
      - checkout
      - run: go get -v -d ./...
      - run: go install -v ./...

workflows:
  version: 2
  test-build-deploy:
    jobs:

      - test:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /.*/

      - build:
        requires:
          - test
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /.*/
