version: 2
jobs:

  test:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/boomfunc/base

    steps:
      - checkout
      - run: go get -v -d -t ./...
      - run: go test -v -cover ./...
      # - run: go test -v -race -cover ./...


  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/boomfunc/base

    steps:
      - checkout
      - run: go get -v -d ./...
      - run: GOOS=linux GOARCH=amd64 go build -i -v -o /go/bin/base-Linux-x86_64
      # - run: GOOS=darwin GOARCH=amd64 go build -i -v -o /go/bin/base-Darwin-x86_64
      - run: ls -la /go/bin

  deploy:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/boomfunc/base

    steps:
      - go get github.com/tcnksm/ghr
      - ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` /go/bin/

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - test
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build




# curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
#  uname -s
# Linux
# / # uname -m
# x86_64
