version: 2
jobs:

  test:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/boomfunc/base

    steps:
      - checkout
      - run:
        name: Install dependencies
        command: go get -v -d -t ./...
      - run:
        name: Test
        command: go test -v -race -cover ./...


  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/boomfunc/base

    steps:
      - checkout
      - run:
        name: Install dependencies
        command: go get -v -d ./...
      - run:
        name: Build
        command: go install -v ./...

  # deploy:
  #   docker:
  #     - image: python:2.7-alpine
  #   steps:
  #
  #     - restore_cache:
  #         keys:
  #           - pip
  #     - run: pip install awscli==1.15.4
  #     - save_cache:
  #         key: pip
  #         paths:
  #           - "~/.cache/pip"
  #
  #     - attach_workspace:
  #         at: /tmp/workspace
  #     - run:
  #         name: Deploy Master to AWS bucket
  #         command: |
  #           aws s3 sync /tmp/workspace/dist s3://com-jetsmarter-web-app/ --acl public-read --delete

workflows:
  version: 2
  test-build-deploy:
    jobs:

      - test:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /.*/

      - build:
        requires:
          - test
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /.*/
      #
      # - deploy:
      #   requires:
      #     - build
      #   filters:
      #     branches:
      #       ignore: /.*/
      #     tags:
      #       only: /.*/
